### ISSUE TITLE
Step 0 - Identify usecases

### ISSUE THREAD

**Issue by refack** [nodejs/ffi#1]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by refack** [comment]
First thing that came to my mind is WIN32 COM interop. By implementing [`CoCreateInstance`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686615(v=vs.85).aspx) we get the plathura of COM exposed functionality on Windows, such as: shell automation, Office interop, SQL-Server (and other device) drivers, etc.
Probably most useful for @electron and GUI applications, but also for natively running node as a Windows service, and native interaction in IIS.

**Comment by Trott** [comment]
Unarchived this repo so I could close all the PRs and issues. Will re-archive when I'm done.
